site_name: Ohayou

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.ico
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs          # top-level items as tabs (nice visual separation)
    # - navigation.tabs.sticky   # keep tabs visible when scrolling
    - navigation.indexes       # section label opens its index page
    # - toc.integrate            # optional: TOC in the sidebar, less clutter

    - navigation.instant
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - content.tabs.link
    - content.code.copy

nav:
  - Ohayou: ohayou.md
  - Home: index.md
  - vLLM:
    # - vLLM: vllm/index.md
    - Single Request: vllm/open_ai_vllm_example_a_v_t.md
    - Bash online serve: vllm/bash_vllm_serve.md
    - Benchmarks: vllm/benchmarks/performance_eval.md
  - MD format helpers: md_format_helpers.md
  - Docker: docker.md
  - Linux: linux.md
  - Mixture of Experts: moe.md
  - Slurm: slurm/index.md
  - Japanese Phrases:
    - Overview: japanese-phrases/index.md
    - Daily Life:
      - Overview: japanese-phrases/daily-life/index.md
      - Shopping: japanese-phrases/daily-life/shopping.md
    - Greetings:
      - Overview: japanese-phrases/greetings/index.md
      - Casual: japanese-phrases/greetings/casual.md
    - Emotions: japanese-phrases/emotions/index.md
    - Anime/Manga: japanese-phrases/anime-manga/index.md
    

plugins:
  - search:
      lang:
        - en
        - ru
        - ja
        - kz
      separator: '[\s\-,:!=\[\]()"/'']+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
  - tags

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      default_lang: bash
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets

extra_css:
  - assets/extra.css
